import { randomBytes, randomUUID, scrypt as scryptCallback, timingSafeEqual, createHmac } from "node:crypto";
import { promisify } from "node:util";
import { HttpApplication, HttpError, type Json, type Repository, requireFields } from "../shared/core.js";
import { ERROR_KEYS } from "../shared/message-keys.js";
import { SqliteAccountRepository } from "../repositories/sqlite-account.repository.js";
const scrypt=promisify(scryptCallback);
export type Account={id:string;email:string;displayName:string;passwordHash:string;createdAt:string};
export class PasswordHasher { async hash(password:string):Promise<string>{if(password.length<10)throw new HttpError(400,ERROR_KEYS.passwordTooShort);const salt=randomBytes(16).toString("hex");const hash=await scrypt(password,salt,64) as Buffer;return `${salt}:${hash.toString("hex")}`;} async verify(password:string,stored:string):Promise<boolean>{const [salt,hex]=stored.split(":");if(!salt||!hex)return false;const actual=await scrypt(password,salt,64) as Buffer;const expected=Buffer.from(hex,"hex");return actual.length===expected.length&&timingSafeEqual(actual,expected);}}
export class TokenIssuer { constructor(private readonly secret=process.env.AUTH_SECRET??""){} issue(account:Account):string{if(this.secret.length<32)throw new HttpError(503,ERROR_KEYS.secretMissing);const payload=Buffer.from(JSON.stringify({sub:account.id,exp:Date.now()+3_600_000})).toString("base64url");const signature=createHmac("sha256",this.secret).update(payload).digest("base64url");return `${payload}.${signature}`;} verifyBearer(header:unknown):{accountId:string}{if(this.secret.length<32)throw new HttpError(503,ERROR_KEYS.secretMissing);if(typeof header!=="string"||!header.startsWith("Bearer "))throw new HttpError(401,ERROR_KEYS.tokenInvalid);const [payload,signature]=header.slice(7).split(".");if(!payload||!signature)throw new HttpError(401,ERROR_KEYS.tokenInvalid);const expected=createHmac("sha256",this.secret).update(payload).digest();const received=Buffer.from(signature,"base64url");if(expected.length!==received.length||!timingSafeEqual(expected,received))throw new HttpError(401,ERROR_KEYS.tokenInvalid);try{const data=JSON.parse(Buffer.from(payload,"base64url").toString("utf8")) as {sub?:unknown;exp?:unknown};if(typeof data.sub!=="string"||typeof data.exp!=="number"||data.exp<Date.now())throw new Error();return{accountId:data.sub};}catch{throw new HttpError(401,ERROR_KEYS.tokenInvalid);}}}
export class AccountService { constructor(private readonly repository:Repository<Account>,private readonly hasher:PasswordHasher,private readonly tokens:TokenIssuer){} async register(input:unknown){const b=requireFields(input,["email","displayName","password"]);const email=String(b.email).trim().toLowerCase();if(!(email.includes("@")&&email.length<=254))throw new HttpError(400,ERROR_KEYS.emailInvalid);if((await this.repository.list()).some(a=>a.email===email))throw new HttpError(409,ERROR_KEYS.accountExists);const account=await this.repository.save({id:randomUUID(),email,displayName:String(b.displayName).slice(0,80),passwordHash:await this.hasher.hash(String(b.password)),createdAt:new Date().toISOString()});return{id:account.id,email:account.email,displayName:account.displayName};} async login(input:unknown){const b=requireFields(input,["email","password"]);const account=(await this.repository.list()).find(a=>a.email===String(b.email).toLowerCase());if(!account||!await this.hasher.verify(String(b.password),account.passwordHash))throw new HttpError(401,ERROR_KEYS.credentialsInvalid);return{accessToken:this.tokens.issue(account),tokenType:"Bearer",expiresIn:3600};}}
export function createAccountApp(repository:Repository<Account>=new SqliteAccountRepository()):HttpApplication{const app=new HttpApplication("account-service");const tokens=new TokenIssuer();const service=new AccountService(repository,new PasswordHasher(),tokens);app.route("GET","/health",async()=>({body:{service:"accounts",status:"ok"}}));app.route("POST","/accounts/register",async c=>({status:201,body:await service.register(await c.json()) as Json}));app.route("POST","/accounts/login",async c=>({body:await service.login(await c.json()) as Json}));app.route("GET","/accounts/session",async c=>({body:tokens.verifyBearer(c.header.authorization) as Json}));return app;}
