export const ERROR_KEYS = {
  requestTooLarge: "request.body_too_large",
  invalidJson: "request.invalid_json",
  objectRequired: "request.object_required",
  fieldRequired: "request.field_required",
  routeNotFound: "route.not_found",
  internal: "server.internal_error",
  adminRequired: "auth.admin_required",
  passwordTooShort: "account.password_too_short",
  secretMissing: "account.auth_secret_missing",
  emailInvalid: "account.email_invalid",
  nameInvalid: "account.name_invalid",
  phoneInvalid: "account.phone_invalid",
  accountExists: "account.already_exists",
  credentialsInvalid: "account.invalid_credentials",
  tokenInvalid: "account.invalid_token",
  profileInvalid: "account.profile_invalid",
  serviceAuthRequired: "auth.service_required",
  productUnknown: "product.unknown",
  productNotFound: "product.not_found",
  priceInvalid: "product.price_invalid",
  itemCountInvalid: "payment.item_count_invalid",
  quantityInvalid: "payment.quantity_invalid",
  orderNotFound: "order.not_found",
  orderUnavailable: "order.unavailable",
  promotionInvalid: "promotion.invalid",
  promotionInactive: "promotion.inactive",
  returnItemsInvalid: "return.items_invalid",
  returnQuantityInvalid: "return.quantity_invalid",
  returnWindowExpired: "return.window_expired",
  serviceInvalid: "service.invalid"
} as const;

export type ErrorKey = typeof ERROR_KEYS[keyof typeof ERROR_KEYS];
