import { randomUUID } from "node:crypto";
import { HttpApplication, HttpError, type Json, requireFields } from "./core.js";
import { ERROR_KEYS } from "./message-keys.js";
type CheckoutItem={productId:string;quantity:number}; type CatalogProduct={id:string;price:number};
export interface PaymentProvider{createSession(order:{id:string;amount:number;items:CheckoutItem[]}):Promise<{checkoutUrl:string;providerReference:string}>;}
export class DevelopmentPaymentProvider implements PaymentProvider{async createSession(order:{id:string}):Promise<{checkoutUrl:string;providerReference:string}>{return{checkoutUrl:`http://localhost:4173/#/payment?session=${encodeURIComponent(order.id)}`,providerReference:`dev_${order.id}`};}}
export class ProductCatalogClient{constructor(private readonly baseUrl=process.env.PRODUCT_SERVICE_URL??"http://localhost:4002"){}async get(id:string):Promise<CatalogProduct>{const response=await fetch(`${this.baseUrl}/products/${encodeURIComponent(id)}`);if(!response.ok)throw new HttpError(400,ERROR_KEYS.productUnknown,{id});return await response.json() as CatalogProduct;}}
export class PaymentService{constructor(private readonly catalog:ProductCatalogClient,private readonly provider:PaymentProvider){}async checkout(input:unknown){if(typeof input!=="object"||input===null)throw new HttpError(400,ERROR_KEYS.objectRequired);const items=(input as {items?:unknown}).items;if(!Array.isArray(items)||items.length<1||items.length>25)throw new HttpError(400,ERROR_KEYS.itemCountInvalid);let amount=0;const clean:CheckoutItem[]=[];for(const value of items){const b=requireFields(value,["productId"]);const quantity=Number(b.quantity);if(!Number.isInteger(quantity)||quantity<1||quantity>10)throw new HttpError(400,ERROR_KEYS.quantityInvalid);const product=await this.catalog.get(String(b.productId));amount+=product.price*quantity;clean.push({productId:product.id,quantity});}const id=randomUUID();const session=await this.provider.createSession({id,amount,items:clean});return{id,amount,currency:"USD",...session};}}
export function createPaymentApp():HttpApplication{const app=new HttpApplication("payment-service");const service=new PaymentService(new ProductCatalogClient(),new DevelopmentPaymentProvider());app.route("GET","/health",async()=>({body:{service:"payments",status:"ok"}}));app.route("POST","/checkout-sessions",async c=>({status:201,body:await service.checkout(await c.json()) as Json}));return app;}
