import test from "node:test";
import assert from "node:assert/strict";
import { HttpError } from "../../src/shared/core.js";
import { ERROR_KEYS } from "../../src/shared/message-keys.js";
import { PaymentService, WebhookVerifier, type OrderGateway, type Payment, type PaymentProvider, type PaymentRepository } from "../../src/services/payments.service.js";
import type { Order } from "../../src/services/orders.service.js";

const pending:Order={id:"order-1",accountId:"account-1",items:[{productId:"bed",quantity:2,unitPrice:40}],subtotal:80,discount:0,shipping:0,amount:80,currency:"USD",status:"pending",shippingAddress:"1 Pet Street",createdAt:new Date().toISOString()};
class MemoryPayments implements PaymentRepository{records:Payment[]=[];async find(id:string){return this.records.find(item=>item.id===id);}async findByIdempotency(accountId:string,key:string){return this.records.find(item=>item.accountId===accountId&&item.idempotencyKey===key);}async findByProviderReference(reference:string){return this.records.find(item=>item.providerReference===reference);}async save(payment:Payment){const index=this.records.findIndex(item=>item.id===payment.id);if(index>=0)this.records[index]=payment;else this.records.push(payment);return payment;}}
const orders:OrderGateway={async get(){return pending;},async updateStatus(_id,status){return{...pending,status};}};
const provider:PaymentProvider={async createSession(payment){return{checkoutUrl:`https://pay.test/${payment.id}`,providerReference:`provider_${payment.id}`};}};

test("payment service uses trusted totals and returns the same session for a retry",async()=>{const repository=new MemoryPayments();const service=new PaymentService(repository,orders,provider);const first=await service.checkout({orderId:pending.id,paymentMethod:"paypal"},"account-1","checkout_key_1");const retry=await service.checkout({orderId:pending.id,paymentMethod:"paypal"},"account-1","checkout_key_1");assert.equal(first.amount,80);assert.equal(retry.id,first.id);assert.equal(repository.records.length,1);});
test("payment service rejects an order owned by another account",async()=>{const service=new PaymentService(new MemoryPayments(),orders,provider);await assert.rejects(()=>service.checkout({orderId:pending.id,paymentMethod:"card"},"account-2","checkout_key_2"),(error:unknown)=>error instanceof HttpError&&error.key===ERROR_KEYS.paymentOwnershipInvalid);});
test("payment service rejects unsupported methods and missing idempotency keys",async()=>{const service=new PaymentService(new MemoryPayments(),orders,provider);await assert.rejects(()=>service.checkout({orderId:pending.id,paymentMethod:"cash"},"account-1","checkout_key_3"),(error:unknown)=>error instanceof HttpError&&error.key===ERROR_KEYS.paymentMethodInvalid);await assert.rejects(()=>service.checkout({orderId:pending.id,paymentMethod:"card"},"account-1",undefined),(error:unknown)=>error instanceof HttpError&&error.key===ERROR_KEYS.paymentIdempotencyInvalid);});
test("only a valid signed webhook marks a payment paid",async()=>{const repository=new MemoryPayments();let updated=false;const gateway:OrderGateway={async get(){return pending;},async updateStatus(){updated=true;return{...pending,status:"paid"};}};const service=new PaymentService(repository,gateway,provider);const payment=await service.checkout({orderId:pending.id,paymentMethod:"card"},"account-1","checkout_key_4");const event={providerReference:payment.providerReference,status:"paid" as const};const verifier=new WebhookVerifier("test-webhook-secret-at-least-32-characters");await assert.rejects(()=>service.processWebhook(event,"bad",verifier),(error:unknown)=>error instanceof HttpError&&error.key===ERROR_KEYS.webhookSignatureInvalid);assert.equal(updated,false);const paid=await service.processWebhook(event,verifier.sign(event),verifier);assert.equal(paid.status,"paid");assert.equal(updated,true);});
